export const images = {
  heroFighter: "/photos/mayuthai.png",
  gymInterior: "/photos/mayuthai.png",
  handWraps: "/photos/mma.png",
  trainingKick: "/photos/mayuthai.png",
  cageEvent: "/photos/upcomming-events.png",
  cageEventAlt: "/photos/upcomming-events-1.png",
  cageFighter: "/photos/mma.png",
  mma: "/photos/mma.png",
  champion: "/photos/achivements.png",
  achievements: "/photos/achivements.png",
  podcastLogo: "/photos/mayuthai.png",
  membershipPoster: "/photos/mayuthai.png",
  schedulePoster: "/photos/mma.png",
} as const;
