export const images = {
  heroFighter: "/photos/mayuthai.png",
  gymInterior: "/photos/mayuthai.png",
  handWraps: "/photos/mma.png",
  trainingKick: "/photos/mayuthai.png",
  cageEvent: "/photos/upcomming-events.png",
  cageEventAlt: "/photos/upcomming-events-1.png",
  cageFighter: "/photos/mma.png",
  mma: "/photos/mma.png",
  champion: "/photos/achivements.png",
  achievements: "/photos/achivements.png",
  podcastLogo: "/photos/upcomming-podcast.png",
  membershipPoster: "/photos/mayuthai.png",
  schedulePoster: "/photos/mma.png",
  fightStore: "/photos/fight-store.png",
  storyLogo: "/photos/our-story-logo.png",
  coverHome: "/photos/cover-background-home.png",
  fitness: "/photos/fitness.png",
  kidsMuayThai: "/photos/kids-muaythai.png",
  sakYantSeal: "/photos/logo-sakyant-bg.png",
} as const;
